In [1]:
# Input
name = input("Enter name: ")

# Output
print(name)

Fendy


In [4]:
# Variable

a = 10
a = "Fendy"
a = 10.45

type(a)

float

In [5]:
# Selection

a = 10

if(a > 10):
    print("a is greater than 10")
elif(a < 10):
    print("a is less than 10")
else:
    print("a is 10")

a is 10


In [8]:
# Repetition (Looping)

# For loop
for i in range(10):
    print(i)
for i in [13, 35, 21]:
    print(i)

# While loop
a = 10
while(a > 0):
    print(a)
    a -= 1

0
1
2
3
4
5
6
7
8
9
13
35
21
10
9
8
7
6
5
4
3
2
1


In [9]:
def sumNumber(a, b):
    return a+b

c = sumNumber(10, 5)
print(c)

15


In [14]:
# Built-in Data Structure

# List -> ordered, mirip array, mutable
list_1 = [1, "2", 3, 4, 5, 5]
print(list_1)

# Tuple -> ordered
tuple_1 = (1, "2", 3, 4, 5, 5)
print(tuple_1)

# Set -> unordered, tidak dapat menampung duplicate value
set_1 = {1, "2", 3, 4, 5, 5}
print(set_1)

# Dictionary -> key-value pair
daftar_ibukota = {"Indonesia":"Jakarta", "Australia":"Canberra", "USA":"Washington DC"}
negara = input("Enter country: ")
print(daftar_ibukota[negara])

[1, '2', 3, 4, 5, 5]
(1, '2', 3, 4, 5, 5)
{1, 3, 4, 5, '2'}
Washington DC


In [18]:
# Data Slicing -> ambil sebagian data dari sebuah array-like

a = [12, 14, 63, 21, 42, 16, 44, 22, 11, 63]
print(a[len(a)-1])
print(a[1:3]) # Ambil elemen a yang berawal dari index 1 dan berakhir sebelum index 3
print(a[0:9:2])

# Format data slicing
#     a:b:c
# a -> start index yang mau diambil
# b -> berakhir sebelum index yang mau diambil
# c -> mau lompat berapa kali

63
[14, 63]
[12, 63, 42, 44, 11]


In [21]:
# Numpy

import numpy as np

arr_1 = np.array([12, 14, 35, 63, 22])
print(arr_1[2:4])

[35 63]


In [27]:
# Ndim -> number of dimension dari sebuah array
# Shape -> kasih tahu bentuk array kita dan dimensinya

arr_1 = np.array([
    [12, 14, 35, 63, 22],
    [34, 23, 55, 77, 11],
    [24, 25, 121, 24, 25]
])

print(arr_1.ndim)
print(arr_1.shape)
print(arr_1[0][0])

2
(3, 5)
12


In [33]:
# Zeros, Ones, Empty -> Bikin array dengan shape yang dikasih

a = np.zeros([2, 5])
print(a)

a = np.ones([2, 5])
print(a)

a = np.empty([2, 6])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1.53778973e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000
  1.11260619e-306 3.76231868e+174]
 [5.24965504e-090 6.87005132e+169 2.81306112e-033 1.95409311e+184
  3.99910963e+252 1.00671539e-046]]


In [37]:
# Random

# Object generator random
generator = np.random.default_rng()

# Generate 0-1
print(generator.random())

# Generate Integer
# Format -> integers(a, b, c)
# a -> start
# b -> end (exclusive)
# c -> jumlah integer yang di-generate
print(generator.integers(5, 11, 10))

0.7095197651032257
[ 8  6  5  5  8  5  7 10  9  6]


In [39]:
# Vstack & Hstack

a = np.array([34, 24, 13, 12])
b = np.array([46, 23, 11, 26])

# Vstack -> Vertical Stack -> Tumpuk array secara vertikal
print(np.vstack([a, b]))

# Hstack -> Horizontal Stack -> Tumpuk array secara horizontal
print(np.hstack([a, b]))

[[34 24 13 12]
 [46 23 11 26]]
[34 24 13 12 46 23 11 26]
